CREATE TABLE WORDLE_FIVE
(
       WORDLE_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)NOT NULL PRIMARY KEY,
       CHAR_1 CHAR(1) NOT NULL,
       CHAR_2 CHAR(1) NOT NULL,
       CHAR_3 CHAR(1) NOT NULL,
       CHAR_4 CHAR(1) NOT NULL,
       CHAR_5 CHAR(1) NOT NULL,
       WORDLE_DATE DATE
);

CREATE TABLE WORD_LIST
(
       SEQ NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)NOT NULL PRIMARY KEY,
       WORD VARCHAR(5),
       WORD_TYPE NUMBER(2)
);

CREATE TABLE WORDLE
(
       WORDLE_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)NOT NULL PRIMARY KEY,
       CHAR_1 CHAR(1) NOT NULL,
       CHAR_2 CHAR(1) NOT NULL,
       CHAR_3 CHAR(1) NOT NULL,
       WORDLE_DATE DATE
);

CREATE TABLE WORDLE_LOG
(
       SEQ NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)NOT NULL PRIMARY KEY,
       OS_USER VARCHAR2(50) NOT NULL,
       IP_ADDRESS VARCHAR2(20) NOT NULL,
       RESPONSE VARCHAR2(1000) NOT NULL,
       WORDLE_TYPE NUMBER(10) NOT NULL,
       WORDLE_DATE DATE
);


